# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.FileField(max_length=250, upload_to=b'', verbose_name=b'path to the video'),
        ),
    ]
