# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20170820_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name=b'Category'),
        ),
        migrations.AlterField(
            model_name='video',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='playlists.Playlist', verbose_name=b'Playlist'),
        ),
    ]
