# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20170820_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name=b'Views'),
        ),
        migrations.AlterField(
            model_name='video',
            name='extension',
            field=models.CharField(max_length=20, verbose_name=b'Extension'),
        ),
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.FileField(max_length=250, upload_to=b'', verbose_name=b'Select'),
        ),
    ]
