# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 21:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0009_watch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name=b'Heart on')),
                ('added_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Heart by')),
                ('comment', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='videos.Comment', verbose_name=b'Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name=b'Liked on')),
                ('added_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Liked by')),
                ('video', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='videos.Video', verbose_name=b'Video')),
            ],
        ),
    ]
