# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0016_auto_20170824_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heart',
            name='added_by',
        ),
        migrations.AddField(
            model_name='heart',
            name='added_by',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name=b'Heart by'),
        ),
    ]
