# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 08:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Added by'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Date added'),
        ),
    ]
