# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20170824_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='video_remaining',
            new_name='value',
        ),
    ]
